books/urls.py
from django.urls import path
from . import views

app_name = "books"
urlpatterns = [
    path('', views.index, name="home")
]

bookstore/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('books.urls')),
    path('accounts/', include('login.urls'))
]

login/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView

app_name = "login"
urlpatterns = [
    path('register/', views.register, name="register"),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(next_page='books:home'), name="logout"),
]

books/models.py
from django.db import models

# Create your models here.

login/models.py
from django.db import models

# Create your models here.

books/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

# Create your views here.


def index(request):
    return render(request, 'index.html')

login/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
# Create your views here.


def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login:login')
    else:
        form = UserCreationForm()
    return render(request, 'register.html', {'form': form})

books/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MHSBooks</title>
    <link rel="stylesheet" href="https://bootswatch.com/4/sketchy/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="https://use.fontawesome.com/d1341f9b7a.js"></script>
</head>

<body>

    <div class="content">
        <nav class="navbar navbar-default">
            <div class="logo navbar-header col-log-2 col-md-2 col-sm-3">
                <img src="{% static 'MHSBooks.png' %}" href="{% url 'books:home' %}" />
            </div>

            <div class="navbar-search col-lg-6 col-md-6 col-sm-12 d-flex flex-direction-row">
                <form id="searchForm" class="flex-grow-1">
                    <input type="text" class="form-control" id="searchText" placeholder="Search Books...">
                </form>
                <button type="button" id="submit" class="btn btn-warning mx-3">Search</button>
            </div>
            {% if user.is_authenticated %}
            <div id="logout" class="col-lg-2 col-md-2 col-sm-12">
                <a href="{% url 'login:logout' %}"><button type="button" class="btn btn-link"><strong>Logout</strong></button></a>
            </div>
            {% else %}
            <div id="login" class="col-lg-2 col-md-2 col-sm-12">
                <a href="{% url 'login:login' %}"><button type="button" class="btn btn-link"><strong>Login /
                            Register</strong></button></a>
            </div>
            {% endif %}
        </nav>

        <div class="container">
            
            {% if user.is_authenticated %}
                <div class="mt-3">
                    <h1>Welcome, {{user.username}}</h1>
                </div>
            {% endif %}
            <div id='alert' class="mt-3"></div>
            <table class="table table-hover mt-4">
                <thead>
                    <tr class="text-center row">
                        <th class="col-lg-2 col-md-6 col-sm-6 col-6" scope="col">Cover</th>
                        <th class="col-lg-4 col-md-6 col-sm-6 col-6" scope="col">Title</th>
                        <th class="col-lg-6 col-md-12 col-sm-12" scope="col">Description</th>
                    </tr>
                </thead>
                <tbody id="books">
                </tbody>
            </table>
        </div>
    </div>

    <footer class="page-footer font-small bg-warning" id="footer">
        <div class="footer-copyright text-center py-3">© 2019:
            <a href="#">MHSBooks.com</a>
        </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.3.1.min.js"
        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="{% static 'js/script.js' %}"></script>
</body>

</html>

login/templates/register.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MHSBooks</title>
    <link rel="stylesheet" href="https://bootswatch.com/4/sketchy/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'registration.css' %}">
    <script src="https://use.fontawesome.com/d1341f9b7a.js"></script>
</head>

<body class="row d-flex justify-content-center align-items-center">
    <div class="jumbotron register row">
        <div class="container col-12 d-flex justify-content-center d-flex flex-direction-collumn">
            <div>
                <h1>Create New Account</h1>
                <form action="{% url 'login:register' %}" method="POST">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-warning">Register</button>
                </form>
            </div>
        </div>
    </div>
</body>

</html>